export const newProjectTypes = {
  EDIT_DATA_TYPE: 'EDIT_DATA_TYPE',
  EDIT_PROJECT_NAME: 'EDIT_PROJECT_NAME',
  EDIT_DATA_SOURCE: 'EDIT_DATA_SOURCE',
  EDIT_ON_PREM_INFO: 'EDIT_ON_PREM_INFO',
  RESET_NEW_PROJECT: 'RESET_NEW_PROJECT'
}